name: dbt
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airbnb
    ports:
      - "5431:5432"
    volumes:
      - ./s3data:/s3data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-db-volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5051:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin

volumes:
  postgres-db-volume: